name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: pip install nox==2022.8.7
    - run: pip install poetry==1.1.15
    - run: pip install nox-poetry==1.0.1
    - run: nox
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}